[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "d21b6b0b5d40803c929af82d81700721693551e8"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[LaMEM.download]]
    sha256 = "a720197d2acc9d561effafbece9ec375b8f8d2c46658fb7e6d3f6cdaef57ee1b"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.3+0/LaMEM.v2.1.3.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "329f1a54905382cb70ad6047f350eaf1a243ba7f"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "f00272562fac9fca83cf6384e3d1ad4aef2e310f7b59b44103dd6e738da05380"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-apple-darwin-libgfortran4-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "cbb4d83037a6b90cdc23f3e1073979da0ab826a5"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "c3e4ded7c9d24f093a0c9043dbe4c4363ef80b5bf2efc074af773bc72bfb4541"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "341643ad728f484a3acd1f451881e703fd1a024e"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "c1487775ce8fee93baa7f3cef10d8689feed7a342d301d064a07088adaf4cf26"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-linux-gnu-libgfortran4-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "cd461744844630cc33fbd2e7a8e795b56651d039"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "cb5a373da6c97033c281d313c186dfd8450a77e18db0940cedc0ba20d2a5bc27"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "859353d9363f5dc6d3800bbce6c60e592e42e5f1"
lazy = true
libgfortran_version = "4.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "116efba152a654f617473b9f0182172ff5019056c40f6a798eeac7210278ee3f"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-w64-mingw32-libgfortran4-mpi+microsoftmpi.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "20b303dda90183cf5244c30051ea409a7fb2ec3e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "6e00928334df2d1164b524b1a55a654601e586e1386d6db41aed4ac198c31a81"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "3c153d749eaca8eeb3290147642d2f3634be99c4"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "45442fe2280ffa6f99f11b65337a6081e98c9233cff34da59f9e22638a251a2b"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.2.0+1/LaMEM.v2.2.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
