[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "d21b6b0b5d40803c929af82d81700721693551e8"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[LaMEM.download]]
    sha256 = "a720197d2acc9d561effafbece9ec375b8f8d2c46658fb7e6d3f6cdaef57ee1b"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.3+0/LaMEM.v2.1.3.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "329f1a54905382cb70ad6047f350eaf1a243ba7f"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "f00272562fac9fca83cf6384e3d1ad4aef2e310f7b59b44103dd6e738da05380"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-apple-darwin-libgfortran4-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "341643ad728f484a3acd1f451881e703fd1a024e"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "c1487775ce8fee93baa7f3cef10d8689feed7a342d301d064a07088adaf4cf26"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-linux-gnu-libgfortran4-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "859353d9363f5dc6d3800bbce6c60e592e42e5f1"
lazy = true
libgfortran_version = "4.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "116efba152a654f617473b9f0182172ff5019056c40f6a798eeac7210278ee3f"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-w64-mingw32-libgfortran4-mpi+microsoftmpi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "6ce6e487b09ae9bc0a9bc865c9fd512088448286"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "92fa020f344add861b3219a3b1948a6ec51bcc5ad99041f511b7a8865edab194"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.3.0+0/LaMEM.v3.3.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "4cdd14d018da31b479d7cbde9215db082dc6246f"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "bdb088e2c69676e23160448aa39d7b8d4be7c64b8a59eedbf74bbc1cf7654faa"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.3.0+0/LaMEM.v3.3.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "c90ce53d873291a20beefe1e8ebf892756e91d5f"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "603b4840e5a0e33b57c81086b668cb1d6599e427378a42725a3ee195a048457b"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.3.0+0/LaMEM.v3.3.0.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "75d2defa10a19abf3a4437e09c14cc4876ab22af"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "b67aeedcb67be961559a4d50b0a4050762cb2ec312fdd1f69874a89c630adfc2"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.3.0+0/LaMEM.v3.3.0.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
