[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "d21b6b0b5d40803c929af82d81700721693551e8"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[LaMEM.download]]
    sha256 = "a720197d2acc9d561effafbece9ec375b8f8d2c46658fb7e6d3f6cdaef57ee1b"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.3+0/LaMEM.v2.1.3.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "329f1a54905382cb70ad6047f350eaf1a243ba7f"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "f00272562fac9fca83cf6384e3d1ad4aef2e310f7b59b44103dd6e738da05380"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-apple-darwin-libgfortran4-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "341643ad728f484a3acd1f451881e703fd1a024e"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "c1487775ce8fee93baa7f3cef10d8689feed7a342d301d064a07088adaf4cf26"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-linux-gnu-libgfortran4-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "859353d9363f5dc6d3800bbce6c60e592e42e5f1"
lazy = true
libgfortran_version = "4.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "116efba152a654f617473b9f0182172ff5019056c40f6a798eeac7210278ee3f"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+1/LaMEM.v2.1.4.x86_64-w64-mingw32-libgfortran4-mpi+microsoftmpi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "8c104828d66baaf4e2ca9b12719eaaf623c25af0"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "947295947a8d4a2bd4ae84f53d02b42509136fdff53f0fa9b941a9b9c96c2ea5"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.3.0+0/LaMEM.v3.3.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "152600a536cc8687284e17c705bd61644f956c82"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "80a0f9087b1b5d6f1f4a9e6d954ffe4efbf9af278f418486f0741e25d4a55cd9"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.3.0+0/LaMEM.v3.3.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "af9a787a06b335cbed1d1122f24e26c4856728fd"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "f64a673d2a0262f85d8bc17d943207e53a29f485800418c045768c2429705bf4"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.3.0+0/LaMEM.v3.3.0.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "4cf912e223a31173f2b48ac33ee099a26dc840d0"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "49ad64c788b2c16c89799a399c2ea36773830b27b8250968c80def5d91222db1"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.3.0+0/LaMEM.v3.3.0.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "c8f197df9e23186f459537332cc139afc1e5e436"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "a6aaeba23ab168297d96ed5d06f566d8c4e117eb40765c9747ced7c68f4d940e"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.4.0+0/LaMEM.v3.4.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "d26b5c0deb3305d890ad32382a02b63bf003a26b"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "f3406490a25d1e2470aa854ecfbe66d1009698eec86005163e13324464d19f90"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.4.0+0/LaMEM.v3.4.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "4287c582537c401d38880cb13ee17eff69ebb5b1"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "c2757fe488d30a0ad6cc0665034f2888a323f813f5666c71bc83da92daa87b90"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.4.0+0/LaMEM.v3.4.0.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "091af1cafa358c86e4251a2d065a300b01d68cd8"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "69ece1d7d51c226ef7b1df055ea16dd68d8b215be95975d49a861781f7652978"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v3.4.0+0/LaMEM.v3.4.0.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
