[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "d21b6b0b5d40803c929af82d81700721693551e8"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[LaMEM.download]]
    sha256 = "a720197d2acc9d561effafbece9ec375b8f8d2c46658fb7e6d3f6cdaef57ee1b"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.3+0/LaMEM.v2.1.3.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "a1414efc01264adb1d6ed3cd99ec72b0c7d17b94"
lazy = true
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "1b9b60c9ffcf1beb63a7c19723603689f15d48a5566ad9cad77a229a000da414"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.3+0/LaMEM.v2.1.3.x86_64-apple-darwin-libgfortran4-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "726d5a3cbfb24e1baa05b8150e7a909b80a44018"
lazy = true
libc = "glibc"
libgfortran_version = "4.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "97b4f8e04f37aa69892bb92b7de054ba917aaf2bb35504bc5b5f762faf6f3a97"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.3+0/LaMEM.v2.1.3.x86_64-linux-gnu-libgfortran4-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "24100542aa5aa6322393007052b0dd91b244013d"
lazy = true
libgfortran_version = "4.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "4b248fe8c4b3e8e14d99bb2ffaa729a9dd0e7d96f4d12b3a192810111eb4914c"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.3+0/LaMEM.v2.1.3.x86_64-w64-mingw32-libgfortran4-mpi+microsoftmpi.tar.gz"
[[LaMEM]]
arch = "aarch64"
git-tree-sha1 = "b2b938e8ee9de6390bb9cb4d57fd8975084f9136"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "91ad6c4f483d5e3d70e65bd31d7145fbb04b90fa36d6638f7943aed18c2dec72"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+0/LaMEM.v2.1.4.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "cbb4d83037a6b90cdc23f3e1073979da0ab826a5"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[LaMEM.download]]
    sha256 = "c3e4ded7c9d24f093a0c9043dbe4c4363ef80b5bf2efc074af773bc72bfb4541"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+0/LaMEM.v2.1.4.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "cd461744844630cc33fbd2e7a8e795b56651d039"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[LaMEM.download]]
    sha256 = "cb5a373da6c97033c281d313c186dfd8450a77e18db0940cedc0ba20d2a5bc27"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+0/LaMEM.v2.1.4.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[LaMEM]]
arch = "x86_64"
git-tree-sha1 = "20b303dda90183cf5244c30051ea409a7fb2ec3e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[LaMEM.download]]
    sha256 = "6e00928334df2d1164b524b1a55a654601e586e1386d6db41aed4ac198c31a81"
    url = "https://github.com/boriskaus/LaMEM_jll.jl/releases/download/LaMEM-v2.1.4+0/LaMEM.v2.1.4.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
